# Generated by Django 2.2.1 on 2019-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
