# Generated by Django 2.2.1 on 2019-06-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_logged_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
