# Generated by Django 2.2.1 on 2019-07-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0003_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Objects',
        ),
    ]
